//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DIME.rc
//
#define IDR_VERSION                    1

#define SUBLANG_ENGLISH_US              0x01
#define LANG_ENGLISH                    0x09
#define IDI_DIMESETTINGS				10
#define IDI_DAYI						11
#define IDI_ARRAY						12
#define IDI_PHONETIC					13
#define IDI_GENERIC						14
#define IDS_DAYI_DESCRIPTION			15
#define	IDS_ARRAY_DESCRIPTION			16
#define	IDS_PHONETIC_DESCRIPTION		17
#define	IDS_GENERIC_DESCRIPTION			18

#define IDIS_DIME						19
#define IDS_IME_MODE                    20
#define IDI_IME_MODE_ON                 21
#define IDI_IME_MODE_OFF                22
#define IDS_DOUBLE_SINGLE_BYTE          23
#define IDI_DOUBLE_SINGLE_BYTE_ON       24
#define IDI_DOUBLE_SINGLE_BYTE_OFF      25

#define IDB_DIME_DAYI_SETTINGS			1000
#define IDB_DIME_ARRAY_SETTINGS			1001
#define IDB_DIME_PHONETIC_SETTINGS		1002
#define IDB_DIME_GENERIC_SETTINGS		1003

#define IDD_DIMESETTINGS				110


#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG_COMMON						111
#define IDD_DIALOG_DICTIONARY					112
#define IDC_EDIT_FONTNAME                       1101
#define IDC_EDIT_FONTPOINT                      1102
#define IDC_BUTTON_CHOOSEFONT                   1103
#define IDC_COL_BG                              1104
#define IDC_COL_FR                              1105
#define IDC_COL_NU	                            1106
#define IDC_COL_PHRASE                          1107
#define IDC_COL_SEBG                            1108
#define IDC_COL_SEFR                            1109
#define IDC_CHECKBOX_ARRAY_FORCESP				1110
#define IDC_CHECKBOX_ARRAY_NOTIFYSP				1111
#define IDC_EDIT_MAXWIDTH                       1112
#define IDC_COMBO_REVERSE_CONVERSION            1113
#define IDC_CHECKBOX_AUTOCOMPOSE                1114
#define IDC_CHECKBOX_CLEAR_ONBEEP				1115
#define IDC_CHECKBOX_DOBEEP						1116
#define IDC_RADIO_KEYBOARD_OPEN                 1117
#define IDC_RADIO_KEYBOARD_CLOSE                1118
#define IDC_CHECKBOX_CUSTOM_TABLE_PRIORITY      1119
#define IDC_CHECKBOX_PHRASE		                1120
#define IDC_CHECKBOX_SPACEASPAGEDOWN            1121
#define IDC_CHECKBOX_SPACEASFIRSTCANDSELKEY     1122
#define IDC_CHECKBOX_ARROWKEYSWPAGES            1123
#define IDC_CHECKBOX_SHOWNOTIFY                 1124
#define IDC_RADIO_OUTPUT_CHT					1125
#define IDC_RADIO_OUTPUT_CHS					1126
#define IDC_STATIC_EDIT_MAXWIDTH				1127
#define IDC_BUTTON_LOAD_MAIN					1128
#define IDC_BUTTON_LOAD_PHRASE					1129
#define IDC_BUTTON_LOAD_ARRAY_SP				1130
#define IDC_BUTTON_LOAD_ARRAY_SC				1131
#define IDC_CHECKBOX_DAYIARTICLEMODE			1132
#define IDC_CHECKBOX_DOBEEPNOTIFY				1133
#define IDC_BUTTON_RESTOREDEFAULT				1134
#define IDC_BUTTON_EXPORT_CUSTOM				1135
#define IDC_BUTTON_IMPORT_CUSTOM				1136
#define IDC_EDIT_CUSTOM_TABLE					1145
#define IDC_BUTTON_LOAD_ARRAY_EXT_B				1146
#define IDC_BUTTON_LOAD_ARRAY_EXT_CD			1147
#define IDC_BUTTON_LOAD_ARRAY_EXT_EFG			1148
#define IDC_BUTTON_LOAD_ARRAY40					1149
#define IDC_COMBO_ARRAY_SCOPE					1150
#define IDC_COMBO_PHONETIC_KEYBOARD				1151
#define IDC_COMBO_DOUBLE_SINGLE_BYTE			1152
#define IDC_COMBO_IME_SHIFT_MODE				1153
#define IDC_STATIC_ARRAY_SCOPE					1154
#define IDC_STATIC_PHONETIC_KEYBOARD			1155
#define IDC_STATIC_DOUBLE_SINGLE_BYTE			1156
#define IDC_STATIC_IME_SHIFT_MODE				1157
#define IDC_CHECKBOX_DOBEEP_CANDI				1158
#define IDC_BUTTON_LOAD_ARRAY_PHRASE			1159
#define IDC_CHECKBOX_ARRAY_SINGLEQUOTE_CUSTOM_PHRASE				1160
#define IDC_STATIC_NUMERIC_KEYPAD				1161
#define IDC_COMBO_NUMERIC_PAD	1162
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
