name: Build


on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'src/**/*.rc'
      - 'src/**/*.def'
      - 'src/**/*.sln'
      - 'src/**/*.vcxproj'
      - 'src/**/*.vcxproj.filters'
      - 'installer/wix/**'
      - 'installer/*.ps1'
  pull_request:
    branches: [master]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'src/**/*.rc'
      - 'src/**/*.def'
      - 'src/**/*.sln'
      - 'src/**/*.vcxproj'
      - 'src/**/*.vcxproj.filters'
      - 'installer/wix/**'
      - 'installer/*.ps1'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: build-installer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-installer:
    name: Build Installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      
      - name: Build All Platforms (Release)
        run: |
          cd src
          msbuild DIME.sln /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /t:DIME
          msbuild DIME.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143 /t:DIME
          msbuild DIME.sln /p:Configuration=Release /p:Platform=ARM64 /p:PlatformToolset=v143 /t:DIME
          msbuild DIME.sln /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /t:DIMESettings
      
      - name: Install WiX Toolset v6
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix extension add WixToolset.Util.wixext/6.0.2 --global
          wix extension add WixToolset.UI.wixext/6.0.2 --global
          wix extension add WixToolset.BootstrapperApplications.wixext/6.0.2 --global

      - name: Build Installer with PowerShell Script
        run: |
          cd installer
          ./deploy-wix-installer.ps1
        shell: pwsh
      
      
      - name: Commit test files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git add src/BuildInfo.h
          git add installer/DIME-Universal.zip
          git add installer/DIME-64bit.msi
          git add installer/DIME-32bit.msi
          git diff --staged --quiet || git commit -m "Update DIME installer and checksums [bot]"
          git pull --rebase
          git push
        shell: pwsh
